/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_alert_notification_0           25
#define gattdb_supported_new_alert_category   27
#define gattdb_new_alert                      29
#define gattdb_supported_unread_alert_category 32
#define gattdb_unread_alert_status            34
#define gattdb_alert_notification_control_point 37
#define gattdb_ota                            38
#define gattdb_ota_control                    40


#endif // __GATT_DB_H
