################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../autogen/sl_board_default_init.c \
../autogen/sl_device_init_clocks.c \
../autogen/sl_event_handler.c \
../autogen/sl_iostream_handles.c \
../autogen/sl_power_manager_handler.c \
../autogen/sl_simple_button_instances.c \
../autogen/sl_simple_led_instances.c \
../autogen/sl_uartdrv_init.c 

OBJS += \
./autogen/sl_board_default_init.o \
./autogen/sl_device_init_clocks.o \
./autogen/sl_event_handler.o \
./autogen/sl_iostream_handles.o \
./autogen/sl_power_manager_handler.o \
./autogen/sl_simple_button_instances.o \
./autogen/sl_simple_led_instances.o \
./autogen/sl_uartdrv_init.o 

C_DEPS += \
./autogen/sl_board_default_init.d \
./autogen/sl_device_init_clocks.d \
./autogen/sl_event_handler.d \
./autogen/sl_iostream_handles.d \
./autogen/sl_power_manager_handler.d \
./autogen/sl_simple_button_instances.d \
./autogen/sl_simple_led_instances.d \
./autogen/sl_uartdrv_init.d 


# Each subdirectory must supply rules for building sources it contributes
autogen/sl_board_default_init.o: ../autogen/sl_board_default_init.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_board_default_init.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_device_init_clocks.o: ../autogen/sl_device_init_clocks.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_device_init_clocks.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_event_handler.o: ../autogen/sl_event_handler.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_event_handler.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_iostream_handles.o: ../autogen/sl_iostream_handles.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_iostream_handles.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_power_manager_handler.o: ../autogen/sl_power_manager_handler.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_power_manager_handler.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_simple_button_instances.o: ../autogen/sl_simple_button_instances.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_simple_button_instances.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_simple_led_instances.o: ../autogen/sl_simple_led_instances.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_simple_led_instances.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

autogen/sl_uartdrv_init.o: ../autogen/sl_uartdrv_init.c autogen/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c99 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32BG22C224F512IM40=1' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_BOARD_NAME="BRD4108A"' '-DSL_BOARD_REV="A03"' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\config" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning\autogen" -I"F:\embedded\embedded_boards\silicon_labs\efr32bg22\led_blink_learning" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFR32BG22/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//app/common/util/app_button_press" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//hardware/driver/configuration_over_swo/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/debug/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/dmadrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/power_manager/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/uartdrv/inc" -I"C:/Users/sudharsan/SimplicityStudio/SDKs/gecko_sdk//platform/service/udelay/inc" -Os -Wall -Wextra -Wconversion -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"autogen/sl_uartdrv_init.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


